version: '3'
services:
  mysql:
    image: mysql
    container_name: book-mysql
    environment:
      MYSQL_DATABASE: 'books'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - $PWD/data:/var/lib/mysql
  test-mysql:
    image: mysql
    container_name: book-mysql-test
    environment:
      MYSQL_DATABASE: 'books'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    volumes:
      - $PWD/test-data:/var/lib/mysql
